/**
 * @file ASPID_FDCAN_NETWORK.c
 *
 * @brief This source file was generated by cantools version 42.0.3 Tue Jul 28 17:46:04 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "ASPID_FDCAN_NETWORK.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int ASPID_FDCAN_NETWORK_gnss_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_gnss_out_t *src_p,
    size_t size)
{
    uint64_t gnss_out_sig492;

    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    gnss_out_sig492 = (uint64_t)src_p->gnss_out_sig492;
    dst_p[0] |= pack_left_shift_u64(gnss_out_sig492, 7u, 0x80u);
    dst_p[1] |= pack_right_shift_u64(gnss_out_sig492, 1u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(gnss_out_sig492, 9u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(gnss_out_sig492, 17u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(gnss_out_sig492, 25u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(gnss_out_sig492, 33u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(gnss_out_sig492, 41u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(gnss_out_sig492, 49u, 0xffu);
    dst_p[8] |= pack_right_shift_u64(gnss_out_sig492, 57u, 0x7fu);

    return (64);
}

int ASPID_FDCAN_NETWORK_gnss_out_unpack(
    struct ASPID_FDCAN_NETWORK_gnss_out_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint64_t gnss_out_sig492;

    if (size < 64u) {
        return (-EINVAL);
    }

    gnss_out_sig492 = unpack_right_shift_u64(src_p[0], 7u, 0x80u);
    gnss_out_sig492 |= unpack_left_shift_u64(src_p[1], 1u, 0xffu);
    gnss_out_sig492 |= unpack_left_shift_u64(src_p[2], 9u, 0xffu);
    gnss_out_sig492 |= unpack_left_shift_u64(src_p[3], 17u, 0xffu);
    gnss_out_sig492 |= unpack_left_shift_u64(src_p[4], 25u, 0xffu);
    gnss_out_sig492 |= unpack_left_shift_u64(src_p[5], 33u, 0xffu);
    gnss_out_sig492 |= unpack_left_shift_u64(src_p[6], 41u, 0xffu);
    gnss_out_sig492 |= unpack_left_shift_u64(src_p[7], 49u, 0xffu);
    gnss_out_sig492 |= unpack_left_shift_u64(src_p[8], 57u, 0x7fu);
    dst_p->gnss_out_sig492 = (int64_t)gnss_out_sig492;

    return (0);
}

int ASPID_FDCAN_NETWORK_gnss_out_init(struct ASPID_FDCAN_NETWORK_gnss_out_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ASPID_FDCAN_NETWORK_gnss_out_t));

    return 0;
}

int64_t ASPID_FDCAN_NETWORK_gnss_out_gnss_out_sig492_encode(double value)
{
    return (int64_t)(value);
}

double ASPID_FDCAN_NETWORK_gnss_out_gnss_out_sig492_decode(int64_t value)
{
    return ((double)value);
}

bool ASPID_FDCAN_NETWORK_gnss_out_gnss_out_sig492_is_in_range(int64_t value)
{
    return ((value >= 0ll) && (value <= 1ll));
}

bool ASPID_FDCAN_NETWORK_gnss_out_gnss_out_sig492_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int ASPID_FDCAN_NETWORK_imu_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_imu_out_t *src_p,
    size_t size)
{
    uint64_t imu_out_sig114;

    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    imu_out_sig114 = (uint64_t)src_p->imu_out_sig114;
    dst_p[0] |= pack_left_shift_u64(imu_out_sig114, 7u, 0x80u);
    dst_p[1] |= pack_right_shift_u64(imu_out_sig114, 1u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(imu_out_sig114, 9u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(imu_out_sig114, 17u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(imu_out_sig114, 25u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(imu_out_sig114, 33u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(imu_out_sig114, 41u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(imu_out_sig114, 49u, 0xffu);
    dst_p[8] |= pack_right_shift_u64(imu_out_sig114, 57u, 0x7fu);

    return (64);
}

int ASPID_FDCAN_NETWORK_imu_out_unpack(
    struct ASPID_FDCAN_NETWORK_imu_out_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint64_t imu_out_sig114;

    if (size < 64u) {
        return (-EINVAL);
    }

    imu_out_sig114 = unpack_right_shift_u64(src_p[0], 7u, 0x80u);
    imu_out_sig114 |= unpack_left_shift_u64(src_p[1], 1u, 0xffu);
    imu_out_sig114 |= unpack_left_shift_u64(src_p[2], 9u, 0xffu);
    imu_out_sig114 |= unpack_left_shift_u64(src_p[3], 17u, 0xffu);
    imu_out_sig114 |= unpack_left_shift_u64(src_p[4], 25u, 0xffu);
    imu_out_sig114 |= unpack_left_shift_u64(src_p[5], 33u, 0xffu);
    imu_out_sig114 |= unpack_left_shift_u64(src_p[6], 41u, 0xffu);
    imu_out_sig114 |= unpack_left_shift_u64(src_p[7], 49u, 0xffu);
    imu_out_sig114 |= unpack_left_shift_u64(src_p[8], 57u, 0x7fu);
    dst_p->imu_out_sig114 = (int64_t)imu_out_sig114;

    return (0);
}

int ASPID_FDCAN_NETWORK_imu_out_init(struct ASPID_FDCAN_NETWORK_imu_out_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ASPID_FDCAN_NETWORK_imu_out_t));

    return 0;
}

int64_t ASPID_FDCAN_NETWORK_imu_out_imu_out_sig114_encode(double value)
{
    return (int64_t)(value);
}

double ASPID_FDCAN_NETWORK_imu_out_imu_out_sig114_decode(int64_t value)
{
    return ((double)value);
}

bool ASPID_FDCAN_NETWORK_imu_out_imu_out_sig114_is_in_range(int64_t value)
{
    return ((value >= 0ll) && (value <= 1ll));
}

bool ASPID_FDCAN_NETWORK_imu_out_imu_out_sig114_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int ASPID_FDCAN_NETWORK_imu_high_g_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_imu_high_g_out_t *src_p,
    size_t size)
{
    uint64_t imu_high_g_out_sig164;

    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    imu_high_g_out_sig164 = (uint64_t)src_p->imu_high_g_out_sig164;
    dst_p[0] |= pack_left_shift_u64(imu_high_g_out_sig164, 7u, 0x80u);
    dst_p[1] |= pack_right_shift_u64(imu_high_g_out_sig164, 1u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(imu_high_g_out_sig164, 9u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(imu_high_g_out_sig164, 17u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(imu_high_g_out_sig164, 25u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(imu_high_g_out_sig164, 33u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(imu_high_g_out_sig164, 41u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(imu_high_g_out_sig164, 49u, 0xffu);
    dst_p[8] |= pack_right_shift_u64(imu_high_g_out_sig164, 57u, 0x7fu);

    return (64);
}

int ASPID_FDCAN_NETWORK_imu_high_g_out_unpack(
    struct ASPID_FDCAN_NETWORK_imu_high_g_out_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint64_t imu_high_g_out_sig164;

    if (size < 64u) {
        return (-EINVAL);
    }

    imu_high_g_out_sig164 = unpack_right_shift_u64(src_p[0], 7u, 0x80u);
    imu_high_g_out_sig164 |= unpack_left_shift_u64(src_p[1], 1u, 0xffu);
    imu_high_g_out_sig164 |= unpack_left_shift_u64(src_p[2], 9u, 0xffu);
    imu_high_g_out_sig164 |= unpack_left_shift_u64(src_p[3], 17u, 0xffu);
    imu_high_g_out_sig164 |= unpack_left_shift_u64(src_p[4], 25u, 0xffu);
    imu_high_g_out_sig164 |= unpack_left_shift_u64(src_p[5], 33u, 0xffu);
    imu_high_g_out_sig164 |= unpack_left_shift_u64(src_p[6], 41u, 0xffu);
    imu_high_g_out_sig164 |= unpack_left_shift_u64(src_p[7], 49u, 0xffu);
    imu_high_g_out_sig164 |= unpack_left_shift_u64(src_p[8], 57u, 0x7fu);
    dst_p->imu_high_g_out_sig164 = (int64_t)imu_high_g_out_sig164;

    return (0);
}

int ASPID_FDCAN_NETWORK_imu_high_g_out_init(struct ASPID_FDCAN_NETWORK_imu_high_g_out_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ASPID_FDCAN_NETWORK_imu_high_g_out_t));

    return 0;
}

int64_t ASPID_FDCAN_NETWORK_imu_high_g_out_imu_high_g_out_sig164_encode(double value)
{
    return (int64_t)(value);
}

double ASPID_FDCAN_NETWORK_imu_high_g_out_imu_high_g_out_sig164_decode(int64_t value)
{
    return ((double)value);
}

bool ASPID_FDCAN_NETWORK_imu_high_g_out_imu_high_g_out_sig164_is_in_range(int64_t value)
{
    return ((value >= 0ll) && (value <= 1ll));
}

bool ASPID_FDCAN_NETWORK_imu_high_g_out_imu_high_g_out_sig164_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int ASPID_FDCAN_NETWORK_bar_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_bar_out_t *src_p,
    size_t size)
{
    uint64_t bar_out_sig484;

    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    bar_out_sig484 = (uint64_t)src_p->bar_out_sig484;
    dst_p[0] |= pack_left_shift_u64(bar_out_sig484, 7u, 0x80u);
    dst_p[1] |= pack_right_shift_u64(bar_out_sig484, 1u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(bar_out_sig484, 9u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(bar_out_sig484, 17u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(bar_out_sig484, 25u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(bar_out_sig484, 33u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(bar_out_sig484, 41u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(bar_out_sig484, 49u, 0xffu);
    dst_p[8] |= pack_right_shift_u64(bar_out_sig484, 57u, 0x7fu);

    return (64);
}

int ASPID_FDCAN_NETWORK_bar_out_unpack(
    struct ASPID_FDCAN_NETWORK_bar_out_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint64_t bar_out_sig484;

    if (size < 64u) {
        return (-EINVAL);
    }

    bar_out_sig484 = unpack_right_shift_u64(src_p[0], 7u, 0x80u);
    bar_out_sig484 |= unpack_left_shift_u64(src_p[1], 1u, 0xffu);
    bar_out_sig484 |= unpack_left_shift_u64(src_p[2], 9u, 0xffu);
    bar_out_sig484 |= unpack_left_shift_u64(src_p[3], 17u, 0xffu);
    bar_out_sig484 |= unpack_left_shift_u64(src_p[4], 25u, 0xffu);
    bar_out_sig484 |= unpack_left_shift_u64(src_p[5], 33u, 0xffu);
    bar_out_sig484 |= unpack_left_shift_u64(src_p[6], 41u, 0xffu);
    bar_out_sig484 |= unpack_left_shift_u64(src_p[7], 49u, 0xffu);
    bar_out_sig484 |= unpack_left_shift_u64(src_p[8], 57u, 0x7fu);
    dst_p->bar_out_sig484 = (int64_t)bar_out_sig484;

    return (0);
}

int ASPID_FDCAN_NETWORK_bar_out_init(struct ASPID_FDCAN_NETWORK_bar_out_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ASPID_FDCAN_NETWORK_bar_out_t));

    return 0;
}

int64_t ASPID_FDCAN_NETWORK_bar_out_bar_out_sig484_encode(double value)
{
    return (int64_t)(value);
}

double ASPID_FDCAN_NETWORK_bar_out_bar_out_sig484_decode(int64_t value)
{
    return ((double)value);
}

bool ASPID_FDCAN_NETWORK_bar_out_bar_out_sig484_is_in_range(int64_t value)
{
    return ((value >= 0ll) && (value <= 1ll));
}

bool ASPID_FDCAN_NETWORK_bar_out_bar_out_sig484_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int ASPID_FDCAN_NETWORK_airbrake_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_airbrake_out_t *src_p,
    size_t size)
{
    uint32_t airbrake_out_sig215;

    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    airbrake_out_sig215 = (uint32_t)src_p->airbrake_out_sig215;
    dst_p[0] |= pack_left_shift_u32(airbrake_out_sig215, 1u, 0xfeu);
    dst_p[1] |= pack_right_shift_u32(airbrake_out_sig215, 7u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(airbrake_out_sig215, 15u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(airbrake_out_sig215, 23u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(airbrake_out_sig215, 31u, 0x01u);

    return (64);
}

int ASPID_FDCAN_NETWORK_airbrake_out_unpack(
    struct ASPID_FDCAN_NETWORK_airbrake_out_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t airbrake_out_sig215;

    if (size < 64u) {
        return (-EINVAL);
    }

    airbrake_out_sig215 = unpack_right_shift_u32(src_p[0], 1u, 0xfeu);
    airbrake_out_sig215 |= unpack_left_shift_u32(src_p[1], 7u, 0xffu);
    airbrake_out_sig215 |= unpack_left_shift_u32(src_p[2], 15u, 0xffu);
    airbrake_out_sig215 |= unpack_left_shift_u32(src_p[3], 23u, 0xffu);
    airbrake_out_sig215 |= unpack_left_shift_u32(src_p[4], 31u, 0x01u);
    dst_p->airbrake_out_sig215 = (int32_t)airbrake_out_sig215;

    return (0);
}

int ASPID_FDCAN_NETWORK_airbrake_out_init(struct ASPID_FDCAN_NETWORK_airbrake_out_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ASPID_FDCAN_NETWORK_airbrake_out_t));

    return 0;
}

int32_t ASPID_FDCAN_NETWORK_airbrake_out_airbrake_out_sig215_encode(double value)
{
    return (int32_t)(value);
}

double ASPID_FDCAN_NETWORK_airbrake_out_airbrake_out_sig215_decode(int32_t value)
{
    return ((double)value);
}

bool ASPID_FDCAN_NETWORK_airbrake_out_airbrake_out_sig215_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 1));
}

bool ASPID_FDCAN_NETWORK_airbrake_out_airbrake_out_sig215_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int ASPID_FDCAN_NETWORK_rf_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_rf_out_t *src_p,
    size_t size)
{
    uint64_t rf_out_sig264;

    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    rf_out_sig264 = (uint64_t)src_p->rf_out_sig264;
    dst_p[0] |= pack_left_shift_u64(rf_out_sig264, 7u, 0x80u);
    dst_p[1] |= pack_right_shift_u64(rf_out_sig264, 1u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(rf_out_sig264, 9u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(rf_out_sig264, 17u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(rf_out_sig264, 25u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(rf_out_sig264, 33u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(rf_out_sig264, 41u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(rf_out_sig264, 49u, 0xffu);
    dst_p[8] |= pack_right_shift_u64(rf_out_sig264, 57u, 0x7fu);

    return (64);
}

int ASPID_FDCAN_NETWORK_rf_out_unpack(
    struct ASPID_FDCAN_NETWORK_rf_out_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint64_t rf_out_sig264;

    if (size < 64u) {
        return (-EINVAL);
    }

    rf_out_sig264 = unpack_right_shift_u64(src_p[0], 7u, 0x80u);
    rf_out_sig264 |= unpack_left_shift_u64(src_p[1], 1u, 0xffu);
    rf_out_sig264 |= unpack_left_shift_u64(src_p[2], 9u, 0xffu);
    rf_out_sig264 |= unpack_left_shift_u64(src_p[3], 17u, 0xffu);
    rf_out_sig264 |= unpack_left_shift_u64(src_p[4], 25u, 0xffu);
    rf_out_sig264 |= unpack_left_shift_u64(src_p[5], 33u, 0xffu);
    rf_out_sig264 |= unpack_left_shift_u64(src_p[6], 41u, 0xffu);
    rf_out_sig264 |= unpack_left_shift_u64(src_p[7], 49u, 0xffu);
    rf_out_sig264 |= unpack_left_shift_u64(src_p[8], 57u, 0x7fu);
    dst_p->rf_out_sig264 = (int64_t)rf_out_sig264;

    return (0);
}

int ASPID_FDCAN_NETWORK_rf_out_init(struct ASPID_FDCAN_NETWORK_rf_out_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ASPID_FDCAN_NETWORK_rf_out_t));

    return 0;
}

int64_t ASPID_FDCAN_NETWORK_rf_out_rf_out_sig264_encode(double value)
{
    return (int64_t)(value);
}

double ASPID_FDCAN_NETWORK_rf_out_rf_out_sig264_decode(int64_t value)
{
    return ((double)value);
}

bool ASPID_FDCAN_NETWORK_rf_out_rf_out_sig264_is_in_range(int64_t value)
{
    return ((value >= 0ll) && (value <= 1ll));
}

bool ASPID_FDCAN_NETWORK_rf_out_rf_out_sig264_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int ASPID_FDCAN_NETWORK_pyro_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_pyro_out_t *src_p,
    size_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    dst_p[0] |= pack_left_shift_u8(src_p->pyro_out_sig75, 1u, 0x02u);

    return (64);
}

int ASPID_FDCAN_NETWORK_pyro_out_unpack(
    struct ASPID_FDCAN_NETWORK_pyro_out_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    dst_p->pyro_out_sig75 = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    return (0);
}

int ASPID_FDCAN_NETWORK_pyro_out_init(struct ASPID_FDCAN_NETWORK_pyro_out_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ASPID_FDCAN_NETWORK_pyro_out_t));

    return 0;
}

uint8_t ASPID_FDCAN_NETWORK_pyro_out_pyro_out_sig75_encode(double value)
{
    return (uint8_t)(value);
}

double ASPID_FDCAN_NETWORK_pyro_out_pyro_out_sig75_decode(uint8_t value)
{
    return ((double)value);
}

bool ASPID_FDCAN_NETWORK_pyro_out_pyro_out_sig75_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool ASPID_FDCAN_NETWORK_pyro_out_pyro_out_sig75_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int ASPID_FDCAN_NETWORK_vsensing_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_vsensing_out_t *src_p,
    size_t size)
{
    uint32_t vsensing_out_sig452;

    if (size < 32u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 32);

    vsensing_out_sig452 = (uint32_t)src_p->vsensing_out_sig452;
    dst_p[0] |= pack_left_shift_u32(vsensing_out_sig452, 1u, 0xfeu);
    dst_p[1] |= pack_right_shift_u32(vsensing_out_sig452, 7u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(vsensing_out_sig452, 15u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(vsensing_out_sig452, 23u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(vsensing_out_sig452, 31u, 0x01u);

    return (32);
}

int ASPID_FDCAN_NETWORK_vsensing_out_unpack(
    struct ASPID_FDCAN_NETWORK_vsensing_out_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t vsensing_out_sig452;

    if (size < 32u) {
        return (-EINVAL);
    }

    vsensing_out_sig452 = unpack_right_shift_u32(src_p[0], 1u, 0xfeu);
    vsensing_out_sig452 |= unpack_left_shift_u32(src_p[1], 7u, 0xffu);
    vsensing_out_sig452 |= unpack_left_shift_u32(src_p[2], 15u, 0xffu);
    vsensing_out_sig452 |= unpack_left_shift_u32(src_p[3], 23u, 0xffu);
    vsensing_out_sig452 |= unpack_left_shift_u32(src_p[4], 31u, 0x01u);
    dst_p->vsensing_out_sig452 = (int32_t)vsensing_out_sig452;

    return (0);
}

int ASPID_FDCAN_NETWORK_vsensing_out_init(struct ASPID_FDCAN_NETWORK_vsensing_out_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ASPID_FDCAN_NETWORK_vsensing_out_t));

    return 0;
}

int32_t ASPID_FDCAN_NETWORK_vsensing_out_vsensing_out_sig452_encode(double value)
{
    return (int32_t)(value);
}

double ASPID_FDCAN_NETWORK_vsensing_out_vsensing_out_sig452_decode(int32_t value)
{
    return ((double)value);
}

bool ASPID_FDCAN_NETWORK_vsensing_out_vsensing_out_sig452_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 1));
}

bool ASPID_FDCAN_NETWORK_vsensing_out_vsensing_out_sig452_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int ASPID_FDCAN_NETWORK_isensing_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_isensing_out_t *src_p,
    size_t size)
{
    uint32_t isensing_out_sig402;

    if (size < 32u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 32);

    isensing_out_sig402 = (uint32_t)src_p->isensing_out_sig402;
    dst_p[0] |= pack_left_shift_u32(isensing_out_sig402, 1u, 0xfeu);
    dst_p[1] |= pack_right_shift_u32(isensing_out_sig402, 7u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(isensing_out_sig402, 15u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(isensing_out_sig402, 23u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(isensing_out_sig402, 31u, 0x01u);

    return (32);
}

int ASPID_FDCAN_NETWORK_isensing_out_unpack(
    struct ASPID_FDCAN_NETWORK_isensing_out_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t isensing_out_sig402;

    if (size < 32u) {
        return (-EINVAL);
    }

    isensing_out_sig402 = unpack_right_shift_u32(src_p[0], 1u, 0xfeu);
    isensing_out_sig402 |= unpack_left_shift_u32(src_p[1], 7u, 0xffu);
    isensing_out_sig402 |= unpack_left_shift_u32(src_p[2], 15u, 0xffu);
    isensing_out_sig402 |= unpack_left_shift_u32(src_p[3], 23u, 0xffu);
    isensing_out_sig402 |= unpack_left_shift_u32(src_p[4], 31u, 0x01u);
    dst_p->isensing_out_sig402 = (int32_t)isensing_out_sig402;

    return (0);
}

int ASPID_FDCAN_NETWORK_isensing_out_init(struct ASPID_FDCAN_NETWORK_isensing_out_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ASPID_FDCAN_NETWORK_isensing_out_t));

    return 0;
}

int32_t ASPID_FDCAN_NETWORK_isensing_out_isensing_out_sig402_encode(double value)
{
    return (int32_t)(value);
}

double ASPID_FDCAN_NETWORK_isensing_out_isensing_out_sig402_decode(int32_t value)
{
    return ((double)value);
}

bool ASPID_FDCAN_NETWORK_isensing_out_isensing_out_sig402_is_in_range(int32_t value)
{
    return ((value >= 0) && (value <= 1));
}

bool ASPID_FDCAN_NETWORK_isensing_out_isensing_out_sig402_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int ASPID_FDCAN_NETWORK_config_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_config_out_t *src_p,
    size_t size)
{
    uint64_t config_out_sig168;

    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    config_out_sig168 = (uint64_t)src_p->config_out_sig168;
    dst_p[0] |= pack_left_shift_u64(config_out_sig168, 7u, 0x80u);
    dst_p[1] |= pack_right_shift_u64(config_out_sig168, 1u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(config_out_sig168, 9u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(config_out_sig168, 17u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(config_out_sig168, 25u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(config_out_sig168, 33u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(config_out_sig168, 41u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(config_out_sig168, 49u, 0xffu);
    dst_p[8] |= pack_right_shift_u64(config_out_sig168, 57u, 0x7fu);

    return (64);
}

int ASPID_FDCAN_NETWORK_config_out_unpack(
    struct ASPID_FDCAN_NETWORK_config_out_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint64_t config_out_sig168;

    if (size < 64u) {
        return (-EINVAL);
    }

    config_out_sig168 = unpack_right_shift_u64(src_p[0], 7u, 0x80u);
    config_out_sig168 |= unpack_left_shift_u64(src_p[1], 1u, 0xffu);
    config_out_sig168 |= unpack_left_shift_u64(src_p[2], 9u, 0xffu);
    config_out_sig168 |= unpack_left_shift_u64(src_p[3], 17u, 0xffu);
    config_out_sig168 |= unpack_left_shift_u64(src_p[4], 25u, 0xffu);
    config_out_sig168 |= unpack_left_shift_u64(src_p[5], 33u, 0xffu);
    config_out_sig168 |= unpack_left_shift_u64(src_p[6], 41u, 0xffu);
    config_out_sig168 |= unpack_left_shift_u64(src_p[7], 49u, 0xffu);
    config_out_sig168 |= unpack_left_shift_u64(src_p[8], 57u, 0x7fu);
    dst_p->config_out_sig168 = (int64_t)config_out_sig168;

    return (0);
}

int ASPID_FDCAN_NETWORK_config_out_init(struct ASPID_FDCAN_NETWORK_config_out_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ASPID_FDCAN_NETWORK_config_out_t));

    return 0;
}

int64_t ASPID_FDCAN_NETWORK_config_out_config_out_sig168_encode(double value)
{
    return (int64_t)(value);
}

double ASPID_FDCAN_NETWORK_config_out_config_out_sig168_decode(int64_t value)
{
    return ((double)value);
}

bool ASPID_FDCAN_NETWORK_config_out_config_out_sig168_is_in_range(int64_t value)
{
    return ((value >= 0ll) && (value <= 1ll));
}

bool ASPID_FDCAN_NETWORK_config_out_config_out_sig168_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int ASPID_FDCAN_NETWORK_emer_deploy_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_emer_deploy_out_t *src_p,
    size_t size)
{
    uint8_t emer_deploy_out_sig456;

    if (size < 32u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 32);

    emer_deploy_out_sig456 = (uint8_t)src_p->emer_deploy_out_sig456;
    dst_p[0] |= pack_left_shift_u8(emer_deploy_out_sig456, 1u, 0x02u);

    return (32);
}

int ASPID_FDCAN_NETWORK_emer_deploy_out_unpack(
    struct ASPID_FDCAN_NETWORK_emer_deploy_out_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t emer_deploy_out_sig456;

    if (size < 32u) {
        return (-EINVAL);
    }

    emer_deploy_out_sig456 = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    if ((emer_deploy_out_sig456 & (1u << 0)) != 0u) {
        emer_deploy_out_sig456 |= 0xfeu;
    }

    dst_p->emer_deploy_out_sig456 = (int8_t)emer_deploy_out_sig456;

    return (0);
}

int ASPID_FDCAN_NETWORK_emer_deploy_out_init(struct ASPID_FDCAN_NETWORK_emer_deploy_out_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ASPID_FDCAN_NETWORK_emer_deploy_out_t));

    return 0;
}

int8_t ASPID_FDCAN_NETWORK_emer_deploy_out_emer_deploy_out_sig456_encode(double value)
{
    return (int8_t)(value);
}

double ASPID_FDCAN_NETWORK_emer_deploy_out_emer_deploy_out_sig456_decode(int8_t value)
{
    return ((double)value);
}

bool ASPID_FDCAN_NETWORK_emer_deploy_out_emer_deploy_out_sig456_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

bool ASPID_FDCAN_NETWORK_emer_deploy_out_emer_deploy_out_sig456_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}
