/**
 * @file ASPID_FDCAN_NETWORK.h
 *
 * @brief This header file was generated by cantools version 42.0.3 Sat Jul 18 10:38:15 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef ASPID_FDCAN_NETWORK_H
#define ASPID_FDCAN_NETWORK_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define ASPID_FDCAN_NETWORK_GNSS_OUT_FRAME_ID (0x00u)
#define ASPID_FDCAN_NETWORK_IMU_OUT_FRAME_ID (0x01u)
#define ASPID_FDCAN_NETWORK_IMU_HIGH_G_OUT_FRAME_ID (0x02u)
#define ASPID_FDCAN_NETWORK_BAR_OUT_FRAME_ID (0x03u)
#define ASPID_FDCAN_NETWORK_AIRBRAKE_OUT_FRAME_ID (0x04u)
#define ASPID_FDCAN_NETWORK_RF_OUT_FRAME_ID (0x05u)
#define ASPID_FDCAN_NETWORK_PYRO_OUT_FRAME_ID (0x06u)
#define ASPID_FDCAN_NETWORK_VSENSING_OUT_FRAME_ID (0x07u)
#define ASPID_FDCAN_NETWORK_ISENSING_OUT_FRAME_ID (0x08u)
#define ASPID_FDCAN_NETWORK_CONFIG_OUT_FRAME_ID (0x09u)
#define ASPID_FDCAN_NETWORK_EMER_DEPLOY_OUT_FRAME_ID (0x0au)

/* Frame lengths in bytes. */
#define ASPID_FDCAN_NETWORK_GNSS_OUT_LENGTH (64u)
#define ASPID_FDCAN_NETWORK_IMU_OUT_LENGTH (64u)
#define ASPID_FDCAN_NETWORK_IMU_HIGH_G_OUT_LENGTH (64u)
#define ASPID_FDCAN_NETWORK_BAR_OUT_LENGTH (64u)
#define ASPID_FDCAN_NETWORK_AIRBRAKE_OUT_LENGTH (64u)
#define ASPID_FDCAN_NETWORK_RF_OUT_LENGTH (64u)
#define ASPID_FDCAN_NETWORK_PYRO_OUT_LENGTH (64u)
#define ASPID_FDCAN_NETWORK_VSENSING_OUT_LENGTH (32u)
#define ASPID_FDCAN_NETWORK_ISENSING_OUT_LENGTH (32u)
#define ASPID_FDCAN_NETWORK_CONFIG_OUT_LENGTH (64u)
#define ASPID_FDCAN_NETWORK_EMER_DEPLOY_OUT_LENGTH (32u)

/* Extended or standard frame types. */
#define ASPID_FDCAN_NETWORK_GNSS_OUT_IS_EXTENDED (0)
#define ASPID_FDCAN_NETWORK_IMU_OUT_IS_EXTENDED (0)
#define ASPID_FDCAN_NETWORK_IMU_HIGH_G_OUT_IS_EXTENDED (0)
#define ASPID_FDCAN_NETWORK_BAR_OUT_IS_EXTENDED (0)
#define ASPID_FDCAN_NETWORK_AIRBRAKE_OUT_IS_EXTENDED (0)
#define ASPID_FDCAN_NETWORK_RF_OUT_IS_EXTENDED (0)
#define ASPID_FDCAN_NETWORK_PYRO_OUT_IS_EXTENDED (0)
#define ASPID_FDCAN_NETWORK_VSENSING_OUT_IS_EXTENDED (0)
#define ASPID_FDCAN_NETWORK_ISENSING_OUT_IS_EXTENDED (0)
#define ASPID_FDCAN_NETWORK_CONFIG_OUT_IS_EXTENDED (0)
#define ASPID_FDCAN_NETWORK_EMER_DEPLOY_OUT_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define ASPID_FDCAN_NETWORK_ISENSING_OUT_ISENSING_OUT_SIG402__CHOICE (0)

/* Frame Names. */
#define ASPID_FDCAN_NETWORK_GNSS_OUT_NAME "GNSS_out"
#define ASPID_FDCAN_NETWORK_IMU_OUT_NAME "IMU_out"
#define ASPID_FDCAN_NETWORK_IMU_HIGH_G_OUT_NAME "IMU_HIGH_G_out"
#define ASPID_FDCAN_NETWORK_BAR_OUT_NAME "BAR_out"
#define ASPID_FDCAN_NETWORK_AIRBRAKE_OUT_NAME "AIRBRAKE_out"
#define ASPID_FDCAN_NETWORK_RF_OUT_NAME "RF_out"
#define ASPID_FDCAN_NETWORK_PYRO_OUT_NAME "PYRO_out"
#define ASPID_FDCAN_NETWORK_VSENSING_OUT_NAME "VSENSING_out"
#define ASPID_FDCAN_NETWORK_ISENSING_OUT_NAME "ISENSING_out"
#define ASPID_FDCAN_NETWORK_CONFIG_OUT_NAME "CONFIG_out"
#define ASPID_FDCAN_NETWORK_EMER_DEPLOY_OUT_NAME "EMER_DEPLOY_out"

/* Signal Names. */
#define ASPID_FDCAN_NETWORK_GNSS_OUT_GNSS_OUT_SIG492_NAME "GNSS_outSig492"
#define ASPID_FDCAN_NETWORK_IMU_OUT_IMU_OUT_SIG114_NAME "IMU_outSig114"
#define ASPID_FDCAN_NETWORK_IMU_HIGH_G_OUT_IMU_HIGH_G_OUT_SIG164_NAME "IMU_HIGH_G_outSig164"
#define ASPID_FDCAN_NETWORK_BAR_OUT_BAR_OUT_SIG484_NAME "BAR_outSig484"
#define ASPID_FDCAN_NETWORK_AIRBRAKE_OUT_AIRBRAKE_OUT_SIG215_NAME "AIRBRAKE_outSig215"
#define ASPID_FDCAN_NETWORK_RF_OUT_RF_OUT_SIG264_NAME "RF_outSig264"
#define ASPID_FDCAN_NETWORK_PYRO_OUT_PYRO_OUT_SIG75_NAME "PYRO_outSig75"
#define ASPID_FDCAN_NETWORK_VSENSING_OUT_VSENSING_OUT_SIG452_NAME "VSENSING_outSig452"
#define ASPID_FDCAN_NETWORK_ISENSING_OUT_ISENSING_OUT_SIG402_NAME "ISENSING_outSig402"
#define ASPID_FDCAN_NETWORK_CONFIG_OUT_CONFIG_OUT_SIG168_NAME "CONFIG_outSig168"
#define ASPID_FDCAN_NETWORK_EMER_DEPLOY_OUT_EMER_DEPLOY_OUT_SIG456_NAME "EMER_DEPLOY_outSig456"

/**
 * Signals in message GNSS_out.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_gnss_out_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int64_t gnss_out_sig492;
};

/**
 * Signals in message IMU_out.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_imu_out_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int64_t imu_out_sig114;
};

/**
 * Signals in message IMU_HIGH_G_out.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_imu_high_g_out_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int64_t imu_high_g_out_sig164;
};

/**
 * Signals in message BAR_out.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_bar_out_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int64_t bar_out_sig484;
};

/**
 * Signals in message AIRBRAKE_out.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_airbrake_out_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int32_t airbrake_out_sig215;
};

/**
 * Signals in message RF_out.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_rf_out_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int64_t rf_out_sig264;
};

/**
 * Signals in message PYRO_out.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_pyro_out_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t pyro_out_sig75;
};

/**
 * Signals in message VSENSING_out.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_vsensing_out_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int32_t vsensing_out_sig452;
};

/**
 * Signals in message ISENSING_out.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_isensing_out_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int32_t isensing_out_sig402;
};

/**
 * Signals in message CONFIG_out.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_config_out_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int64_t config_out_sig168;
};

/**
 * Signals in message EMER_DEPLOY_out.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_emer_deploy_out_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int8_t emer_deploy_out_sig456;
};

/**
 * Pack message GNSS_out.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_gnss_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_gnss_out_t *src_p,
    size_t size);

/**
 * Unpack message GNSS_out.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_gnss_out_unpack(
    struct ASPID_FDCAN_NETWORK_gnss_out_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from GNSS_out.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_gnss_out_init(struct ASPID_FDCAN_NETWORK_gnss_out_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int64_t ASPID_FDCAN_NETWORK_gnss_out_gnss_out_sig492_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ASPID_FDCAN_NETWORK_gnss_out_gnss_out_sig492_decode(int64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_gnss_out_gnss_out_sig492_is_in_range(int64_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_gnss_out_gnss_out_sig492_is_in_phys_range(double value);

/**
 * Pack message IMU_out.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_imu_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_imu_out_t *src_p,
    size_t size);

/**
 * Unpack message IMU_out.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_imu_out_unpack(
    struct ASPID_FDCAN_NETWORK_imu_out_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from IMU_out.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_imu_out_init(struct ASPID_FDCAN_NETWORK_imu_out_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int64_t ASPID_FDCAN_NETWORK_imu_out_imu_out_sig114_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ASPID_FDCAN_NETWORK_imu_out_imu_out_sig114_decode(int64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_imu_out_imu_out_sig114_is_in_range(int64_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_imu_out_imu_out_sig114_is_in_phys_range(double value);

/**
 * Pack message IMU_HIGH_G_out.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_imu_high_g_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_imu_high_g_out_t *src_p,
    size_t size);

/**
 * Unpack message IMU_HIGH_G_out.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_imu_high_g_out_unpack(
    struct ASPID_FDCAN_NETWORK_imu_high_g_out_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from IMU_HIGH_G_out.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_imu_high_g_out_init(struct ASPID_FDCAN_NETWORK_imu_high_g_out_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int64_t ASPID_FDCAN_NETWORK_imu_high_g_out_imu_high_g_out_sig164_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ASPID_FDCAN_NETWORK_imu_high_g_out_imu_high_g_out_sig164_decode(int64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_imu_high_g_out_imu_high_g_out_sig164_is_in_range(int64_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_imu_high_g_out_imu_high_g_out_sig164_is_in_phys_range(double value);

/**
 * Pack message BAR_out.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_bar_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_bar_out_t *src_p,
    size_t size);

/**
 * Unpack message BAR_out.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_bar_out_unpack(
    struct ASPID_FDCAN_NETWORK_bar_out_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BAR_out.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_bar_out_init(struct ASPID_FDCAN_NETWORK_bar_out_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int64_t ASPID_FDCAN_NETWORK_bar_out_bar_out_sig484_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ASPID_FDCAN_NETWORK_bar_out_bar_out_sig484_decode(int64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_bar_out_bar_out_sig484_is_in_range(int64_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_bar_out_bar_out_sig484_is_in_phys_range(double value);

/**
 * Pack message AIRBRAKE_out.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_airbrake_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_airbrake_out_t *src_p,
    size_t size);

/**
 * Unpack message AIRBRAKE_out.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_airbrake_out_unpack(
    struct ASPID_FDCAN_NETWORK_airbrake_out_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AIRBRAKE_out.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_airbrake_out_init(struct ASPID_FDCAN_NETWORK_airbrake_out_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t ASPID_FDCAN_NETWORK_airbrake_out_airbrake_out_sig215_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ASPID_FDCAN_NETWORK_airbrake_out_airbrake_out_sig215_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_airbrake_out_airbrake_out_sig215_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_airbrake_out_airbrake_out_sig215_is_in_phys_range(double value);

/**
 * Pack message RF_out.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_rf_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_rf_out_t *src_p,
    size_t size);

/**
 * Unpack message RF_out.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_rf_out_unpack(
    struct ASPID_FDCAN_NETWORK_rf_out_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RF_out.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_rf_out_init(struct ASPID_FDCAN_NETWORK_rf_out_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int64_t ASPID_FDCAN_NETWORK_rf_out_rf_out_sig264_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ASPID_FDCAN_NETWORK_rf_out_rf_out_sig264_decode(int64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_rf_out_rf_out_sig264_is_in_range(int64_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_rf_out_rf_out_sig264_is_in_phys_range(double value);

/**
 * Pack message PYRO_out.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_pyro_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_pyro_out_t *src_p,
    size_t size);

/**
 * Unpack message PYRO_out.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_pyro_out_unpack(
    struct ASPID_FDCAN_NETWORK_pyro_out_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from PYRO_out.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_pyro_out_init(struct ASPID_FDCAN_NETWORK_pyro_out_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ASPID_FDCAN_NETWORK_pyro_out_pyro_out_sig75_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ASPID_FDCAN_NETWORK_pyro_out_pyro_out_sig75_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_pyro_out_pyro_out_sig75_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_pyro_out_pyro_out_sig75_is_in_phys_range(double value);

/**
 * Pack message VSENSING_out.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_vsensing_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_vsensing_out_t *src_p,
    size_t size);

/**
 * Unpack message VSENSING_out.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_vsensing_out_unpack(
    struct ASPID_FDCAN_NETWORK_vsensing_out_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VSENSING_out.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_vsensing_out_init(struct ASPID_FDCAN_NETWORK_vsensing_out_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t ASPID_FDCAN_NETWORK_vsensing_out_vsensing_out_sig452_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ASPID_FDCAN_NETWORK_vsensing_out_vsensing_out_sig452_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_vsensing_out_vsensing_out_sig452_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_vsensing_out_vsensing_out_sig452_is_in_phys_range(double value);

/**
 * Pack message ISENSING_out.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_isensing_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_isensing_out_t *src_p,
    size_t size);

/**
 * Unpack message ISENSING_out.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_isensing_out_unpack(
    struct ASPID_FDCAN_NETWORK_isensing_out_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ISENSING_out.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_isensing_out_init(struct ASPID_FDCAN_NETWORK_isensing_out_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t ASPID_FDCAN_NETWORK_isensing_out_isensing_out_sig402_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ASPID_FDCAN_NETWORK_isensing_out_isensing_out_sig402_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_isensing_out_isensing_out_sig402_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_isensing_out_isensing_out_sig402_is_in_phys_range(double value);

/**
 * Pack message CONFIG_out.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_config_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_config_out_t *src_p,
    size_t size);

/**
 * Unpack message CONFIG_out.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_config_out_unpack(
    struct ASPID_FDCAN_NETWORK_config_out_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CONFIG_out.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_config_out_init(struct ASPID_FDCAN_NETWORK_config_out_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int64_t ASPID_FDCAN_NETWORK_config_out_config_out_sig168_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ASPID_FDCAN_NETWORK_config_out_config_out_sig168_decode(int64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_config_out_config_out_sig168_is_in_range(int64_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_config_out_config_out_sig168_is_in_phys_range(double value);

/**
 * Pack message EMER_DEPLOY_out.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_emer_deploy_out_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_emer_deploy_out_t *src_p,
    size_t size);

/**
 * Unpack message EMER_DEPLOY_out.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_emer_deploy_out_unpack(
    struct ASPID_FDCAN_NETWORK_emer_deploy_out_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EMER_DEPLOY_out.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_emer_deploy_out_init(struct ASPID_FDCAN_NETWORK_emer_deploy_out_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t ASPID_FDCAN_NETWORK_emer_deploy_out_emer_deploy_out_sig456_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ASPID_FDCAN_NETWORK_emer_deploy_out_emer_deploy_out_sig456_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_emer_deploy_out_emer_deploy_out_sig456_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool ASPID_FDCAN_NETWORK_emer_deploy_out_emer_deploy_out_sig456_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
